/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import static Helpers.ConverterHelper.convertSeparatedStringToStringArray;
import static Helpers.GameHandler.gameHandlerInstance;
import Helpers.ViewHelper;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import static Helpers.ViewHelper.scaleImageInLabel;
import static Helpers.ViewHelper.switchPanelView;
import Views.Base.BaseGameJFrame;
import com.k33ptoo.components.KGradientPanel;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Jani
 */

//Játékot írányító UI és függvényei
public class JFrameHost extends BaseGameJFrame {

    public static JFrameHost jFrameHostInstance;
    int cupsLeft;

    ImageIcon icon = new ImageIcon(".//resources/images/icon.png");

    public JFrameHost() {
        initComponents();
        isPlayer = false;
        this.setMinimumSize(new Dimension(1280, 720));
        setFrameTo16to9WindowedFullScreen();
        setFrameSizeVarsToFrameSize();

        componentLocationAndSize();
        waitingScreen_kGrdntPnl.updateUI();

        gameHost_kGrdntPnl.setVisible(false);
        exit_kGrdntPnl.setVisible(false);

        waitingScreen_kGrdntPnl.setLayout(null);
        gameHost_kGrdntPnl.setLayout(null);
        exit_kGrdntPnl.setLayout(null);

        imageScaler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLyrdPn = new javax.swing.JLayeredPane();
        waitingScreen_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        waitingScreen_jLblPleaseWait = new javax.swing.JLabel();
        waitingScreen_JLblLogo = new javax.swing.JLabel();
        gameHost_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        gameHost_kBttnEndPlayerGame = new com.k33ptoo.components.KButton();
        gameHost_jLblGameName = new javax.swing.JLabel();
        gameHost_jLblPlayerName = new javax.swing.JLabel();
        gameHost_kBttnNextQuestion = new com.k33ptoo.components.KButton();
        gameHost_kBttnShowAnswer = new com.k33ptoo.components.KButton();
        gameHost_jLblQuestion = new javax.swing.JLabel();
        gameHost_jLblHalf = new javax.swing.JLabel();
        gameHost_jLblGroup = new javax.swing.JLabel();
        gameHost_jLblCall = new javax.swing.JLabel();
        gameHost_jLblRefill = new javax.swing.JLabel();
        gameHost_jLblRefillNumber = new javax.swing.JLabel();
        gameHost_jLblCup = new javax.swing.JLabel();
        gameHost_jLblCupNumber = new javax.swing.JLabel();
        gameHost_kBttnRefill = new com.k33ptoo.components.KButton();
        gameHost_jLblPoint = new javax.swing.JLabel();
        exit_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        exit_kBttnExit = new com.k33ptoo.components.KButton();
        exit_kBttnNewGame = new com.k33ptoo.components.KButton();
        exit_JLblLogo = new javax.swing.JLabel();
        exit_kBttnEndGame = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(icon.getImage());
        setName("frame"); // NOI18N
        setResizable(false);

        waitingScreen_kGrdntPnl.setkEndColor(new java.awt.Color(100, 0, 0));
        waitingScreen_kGrdntPnl.setkGradientFocus(1000);
        waitingScreen_kGrdntPnl.setkStartColor(new java.awt.Color(139, 46, 87));

        waitingScreen_jLblPleaseWait.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        waitingScreen_jLblPleaseWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waitingScreen_jLblPleaseWait.setText("Kérlek várj!");

        waitingScreen_JLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waitingScreen_JLblLogo.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        javax.swing.GroupLayout waitingScreen_kGrdntPnlLayout = new javax.swing.GroupLayout(waitingScreen_kGrdntPnl);
        waitingScreen_kGrdntPnl.setLayout(waitingScreen_kGrdntPnlLayout);
        waitingScreen_kGrdntPnlLayout.setHorizontalGroup(
            waitingScreen_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitingScreen_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waitingScreen_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waitingScreen_JLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waitingScreen_jLblPleaseWait, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap())
        );
        waitingScreen_kGrdntPnlLayout.setVerticalGroup(
            waitingScreen_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitingScreen_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitingScreen_JLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(waitingScreen_jLblPleaseWait, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        gameHost_kGrdntPnl.setkEndColor(new java.awt.Color(100, 0, 0));
        gameHost_kGrdntPnl.setkGradientFocus(1000);
        gameHost_kGrdntPnl.setkStartColor(new java.awt.Color(139, 46, 87));

        gameHost_kBttnEndPlayerGame.setBorder(null);
        gameHost_kBttnEndPlayerGame.setText("Játékos kidölt");
        gameHost_kBttnEndPlayerGame.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_kBttnEndPlayerGame.setkBorderRadius(50);
        gameHost_kBttnEndPlayerGame.setkEndColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnEndPlayerGame.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnEndPlayerGame.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        gameHost_kBttnEndPlayerGame.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnEndPlayerGame.setkIndicatorThickness(0);
        gameHost_kBttnEndPlayerGame.setkStartColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnEndPlayerGame.setPreferredSize(new java.awt.Dimension(200, 50));
        gameHost_kBttnEndPlayerGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameHost_kBttnEndPlayerGameMouseClicked(evt);
            }
        });

        gameHost_jLblGameName.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_jLblGameName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblGameName.setText("Játék neve:");
        gameHost_jLblGameName.setPreferredSize(new java.awt.Dimension(366, 50));

        gameHost_jLblPlayerName.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_jLblPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblPlayerName.setText("Játékos neve:");
        gameHost_jLblPlayerName.setPreferredSize(new java.awt.Dimension(366, 50));

        gameHost_kBttnNextQuestion.setBorder(null);
        gameHost_kBttnNextQuestion.setText("Következő kérdés");
        gameHost_kBttnNextQuestion.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_kBttnNextQuestion.setkBorderRadius(50);
        gameHost_kBttnNextQuestion.setkEndColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnNextQuestion.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnNextQuestion.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        gameHost_kBttnNextQuestion.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnNextQuestion.setkIndicatorThickness(0);
        gameHost_kBttnNextQuestion.setkStartColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnNextQuestion.setPreferredSize(new java.awt.Dimension(200, 50));
        gameHost_kBttnNextQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameHost_kBttnNextQuestionMouseClicked(evt);
            }
        });

        gameHost_kBttnShowAnswer.setBorder(null);
        gameHost_kBttnShowAnswer.setText("Válasz mutatása");
        gameHost_kBttnShowAnswer.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_kBttnShowAnswer.setkBorderRadius(50);
        gameHost_kBttnShowAnswer.setkEndColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnShowAnswer.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnShowAnswer.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        gameHost_kBttnShowAnswer.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnShowAnswer.setkIndicatorThickness(0);
        gameHost_kBttnShowAnswer.setkStartColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnShowAnswer.setPreferredSize(new java.awt.Dimension(200, 50));
        gameHost_kBttnShowAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameHost_kBttnShowAnswerMouseClicked(evt);
            }
        });

        gameHost_jLblQuestion.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_jLblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblQuestion.setText("*insert question here*");

        gameHost_jLblHalf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblHalf.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_jLblGroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblGroup.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_jLblCall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblCall.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_jLblRefill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblRefill.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_jLblRefillNumber.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_jLblRefillNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblRefillNumber.setText("*R.Sz.*");
        gameHost_jLblRefillNumber.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_jLblCup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblCup.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_jLblCupNumber.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_jLblCupNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblCupNumber.setText("*P.Sz.*");
        gameHost_jLblCupNumber.setPreferredSize(new java.awt.Dimension(50, 50));

        gameHost_kBttnRefill.setBorder(null);
        gameHost_kBttnRefill.setText("Poharak újratöltése");
        gameHost_kBttnRefill.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_kBttnRefill.setkBorderRadius(50);
        gameHost_kBttnRefill.setkEndColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnRefill.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnRefill.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        gameHost_kBttnRefill.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        gameHost_kBttnRefill.setkIndicatorThickness(0);
        gameHost_kBttnRefill.setkStartColor(new java.awt.Color(46, 139, 87));
        gameHost_kBttnRefill.setPreferredSize(new java.awt.Dimension(200, 50));
        gameHost_kBttnRefill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameHost_kBttnRefillMouseClicked(evt);
            }
        });

        gameHost_jLblPoint.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameHost_jLblPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameHost_jLblPoint.setText("Pontok:");
        gameHost_jLblPoint.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout gameHost_kGrdntPnlLayout = new javax.swing.GroupLayout(gameHost_kGrdntPnl);
        gameHost_kGrdntPnl.setLayout(gameHost_kGrdntPnlLayout);
        gameHost_kGrdntPnlLayout.setHorizontalGroup(
            gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameHost_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameHost_kGrdntPnlLayout.createSequentialGroup()
                        .addComponent(gameHost_kBttnShowAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(gameHost_kBttnRefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(gameHost_kBttnNextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gameHost_jLblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameHost_kGrdntPnlLayout.createSequentialGroup()
                        .addComponent(gameHost_jLblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblHalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblCall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameHost_kGrdntPnlLayout.createSequentialGroup()
                        .addComponent(gameHost_jLblGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblRefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblRefillNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblCupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_kBttnEndPlayerGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        gameHost_kGrdntPnlLayout.setVerticalGroup(
            gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameHost_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gameHost_jLblGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gameHost_kBttnEndPlayerGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gameHost_jLblCupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gameHost_jLblRefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameHost_jLblCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameHost_jLblRefillNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameHost_kGrdntPnlLayout.createSequentialGroup()
                        .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gameHost_jLblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gameHost_jLblPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gameHost_jLblHalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameHost_jLblCall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(gameHost_jLblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addGroup(gameHost_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameHost_kBttnNextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameHost_kBttnShowAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameHost_kBttnRefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gameHost_kGrdntPnlLayout.createSequentialGroup()
                        .addComponent(gameHost_jLblGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        exit_kGrdntPnl.setkEndColor(new java.awt.Color(100, 0, 0));
        exit_kGrdntPnl.setkGradientFocus(1000);
        exit_kGrdntPnl.setkStartColor(new java.awt.Color(139, 46, 87));

        exit_kBttnExit.setBorder(null);
        exit_kBttnExit.setText("Kilépés");
        exit_kBttnExit.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        exit_kBttnExit.setkBorderRadius(50);
        exit_kBttnExit.setkEndColor(new java.awt.Color(0, 100, 0));
        exit_kBttnExit.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        exit_kBttnExit.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        exit_kBttnExit.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        exit_kBttnExit.setkIndicatorThickness(0);
        exit_kBttnExit.setkStartColor(new java.awt.Color(46, 139, 87));
        exit_kBttnExit.setPreferredSize(new java.awt.Dimension(200, 50));
        exit_kBttnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_kBttnExitMouseClicked(evt);
            }
        });

        exit_kBttnNewGame.setBorder(null);
        exit_kBttnNewGame.setText("Új kihivó");
        exit_kBttnNewGame.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        exit_kBttnNewGame.setkBorderRadius(50);
        exit_kBttnNewGame.setkEndColor(new java.awt.Color(0, 100, 0));
        exit_kBttnNewGame.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        exit_kBttnNewGame.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        exit_kBttnNewGame.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        exit_kBttnNewGame.setkIndicatorThickness(0);
        exit_kBttnNewGame.setkStartColor(new java.awt.Color(46, 139, 87));
        exit_kBttnNewGame.setPreferredSize(new java.awt.Dimension(200, 50));
        exit_kBttnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_kBttnNewGameMouseClicked(evt);
            }
        });

        exit_JLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_JLblLogo.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        exit_kBttnEndGame.setBorder(null);
        exit_kBttnEndGame.setText("Mindenki ittas");
        exit_kBttnEndGame.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        exit_kBttnEndGame.setkBorderRadius(50);
        exit_kBttnEndGame.setkEndColor(new java.awt.Color(0, 100, 0));
        exit_kBttnEndGame.setkHoverEndColor(new java.awt.Color(46, 139, 87));
        exit_kBttnEndGame.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        exit_kBttnEndGame.setkHoverStartColor(new java.awt.Color(0, 100, 0));
        exit_kBttnEndGame.setkIndicatorThickness(0);
        exit_kBttnEndGame.setkStartColor(new java.awt.Color(46, 139, 87));
        exit_kBttnEndGame.setPreferredSize(new java.awt.Dimension(200, 50));
        exit_kBttnEndGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_kBttnEndGameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exit_kGrdntPnlLayout = new javax.swing.GroupLayout(exit_kGrdntPnl);
        exit_kGrdntPnl.setLayout(exit_kGrdntPnlLayout);
        exit_kGrdntPnlLayout.setHorizontalGroup(
            exit_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exit_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exit_JLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(exit_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(0, 588, Short.MAX_VALUE)
                        .addComponent(exit_kBttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(exit_kGrdntPnlLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(exit_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit_kBttnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit_kBttnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exit_kGrdntPnlLayout.setVerticalGroup(
            exit_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit_JLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(exit_kBttnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(exit_kBttnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(exit_kBttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLyrdPn.setLayer(waitingScreen_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(gameHost_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(exit_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLyrdPnLayout = new javax.swing.GroupLayout(jLyrdPn);
        jLyrdPn.setLayout(jLyrdPnLayout);
        jLyrdPnLayout.setHorizontalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameHost_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(exit_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(waitingScreen_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLyrdPnLayout.setVerticalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameHost_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(exit_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(waitingScreen_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLyrdPn)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLyrdPn)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameHost_kBttnEndPlayerGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameHost_kBttnEndPlayerGameMouseClicked
        // TODO add your handling code here:
        switchPanelView(gameHost_kGrdntPnl, exit_kGrdntPnl);
        gameHandlerInstance.endPlayerGame();
    }//GEN-LAST:event_gameHost_kBttnEndPlayerGameMouseClicked

    private void gameHost_kBttnShowAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameHost_kBttnShowAnswerMouseClicked
        // TODO add your handling code here:
        if (cupsLeft != 0) {
            ViewHelper.infoBox("Oszd ki az összes poharad!");
            return;
        }

        gameHandlerInstance.answerQuestion();
        gameHost_jLblPoint.setText("Pontok: " + gameHandlerInstance.getActualPlayer().getScore());

        gameHost_kBttnShowAnswer.setVisible(false);
        gameHost_kBttnEndPlayerGame.setVisible(true);
        if (gameHandlerInstance.getActualPlayer().getRefillsLeft() > 0 && gameHandlerInstance.getActualPlayer().getCupsLeft() != gameHandlerInstance.getGame().getCups()) {
            gameHost_kBttnRefill.setVisible(true);
        }
        if (gameHandlerInstance.getActualPlayer().getCupsLeft() > 0) {
            gameHost_kBttnNextQuestion.setVisible(true);
        }
    }//GEN-LAST:event_gameHost_kBttnShowAnswerMouseClicked

    private void gameHost_kBttnRefillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameHost_kBttnRefillMouseClicked
        // TODO add your handling code here:
        gameHandlerInstance.refillCups();
        gameHost_kBttnRefill.setVisible(false);
    }//GEN-LAST:event_gameHost_kBttnRefillMouseClicked

    private void gameHost_kBttnNextQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameHost_kBttnNextQuestionMouseClicked
        // TODO add your handling code here:
        gameHandlerInstance.callFromHostToPlayer_NextPlayerRound();
    }//GEN-LAST:event_gameHost_kBttnNextQuestionMouseClicked

    private void exit_kBttnNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_kBttnNewGameMouseClicked
        // TODO add your handling code here:
        switchPanelView(exit_kGrdntPnl, waitingScreen_kGrdntPnl);
        gameHandlerInstance.callFromHostToPlayer_CreateNewPlayer();

    }//GEN-LAST:event_exit_kBttnNewGameMouseClicked

    private void exit_kBttnEndGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_kBttnEndGameMouseClicked
        // TODO add your handling code here:
        gameHandlerInstance.endGame();
        this.dispose();

    }//GEN-LAST:event_exit_kBttnEndGameMouseClicked

    private void exit_kBttnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_kBttnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_kBttnExitMouseClicked

    ///SAJÁT ELJÁRÁSOK
    public void displayNewQuestion() {
        cupsLeft = gameHandlerInstance.getActualPlayer().getCupsLeft();

        gameHost_jLblQuestion.setText(gameHandlerInstance.getActualQuestion().getQuestion());
        gameHost_jLblGameName.setText("Játék neve: " + gameHandlerInstance.getGame().getGameName());
        gameHost_jLblPlayerName.setText("Játékos neve: " + gameHandlerInstance.getActualPlayer().getPlayerName());
        gameHost_jLblPoint.setText("Pontok: " + gameHandlerInstance.getActualPlayer().getScore());
        gameHost_jLblRefillNumber.setText("" + gameHandlerInstance.getActualPlayer().getRefillsLeft());
        gameHost_jLblCupNumber.setText(cupsLeft + "/" + gameHandlerInstance.getActualPlayer().getCupsLeft());

        gameHost_kBttnShowAnswer.setVisible(true);
        gameHost_kBttnEndPlayerGame.setVisible(false);
        gameHost_kBttnNextQuestion.setVisible(false);
        gameHost_kBttnRefill.setVisible(false);

        if (gameHandlerInstance.getActualPlayer().getIsHalfingUsed()) {
            gameHost_jLblHalf.setEnabled(false);
        } else {
            gameHost_jLblHalf.setEnabled(true);
        }
        if (gameHandlerInstance.getActualPlayer().getIsCallUsed()) {
            gameHost_jLblCall.setEnabled(false);
        } else {
            gameHost_jLblCall.setEnabled(true);
        }
        if (gameHandlerInstance.getActualPlayer().getIsGroupUsed()) {
            gameHost_jLblGroup.setEnabled(false);
        } else {
            gameHost_jLblGroup.setEnabled(true);
        }

        generateAnswerPanels(gameHost_kGrdntPnl,
                convertSeparatedStringToStringArray(gameHandlerInstance.getActualQuestion().getAnswers()));

        switchPanelView(waitingScreen_kGrdntPnl, gameHost_kGrdntPnl);
    }

    public void imageScaler() {
        scaleImageInLabel(".//resources/images/half.png", gameHost_jLblHalf);
        scaleImageInLabel(".//resources/images/call.png", gameHost_jLblCall);
        scaleImageInLabel(".//resources/images/group.png", gameHost_jLblGroup);
        scaleImageInLabel(".//resources/images/shot.png", gameHost_jLblCup);
        scaleImageInLabel(".//resources/images/refill.png", gameHost_jLblRefill);
    }

    private void componentLocationAndSize() {
        //waitingScreen
        changeBound(waitingScreen_JLblLogo, 0,
                frameHeight / 2 - frameHeight / 3 / 2 - frameHeight / 36,
                frameWidth - frameWidth / 32, frameHeight / 3);
        changeBound(waitingScreen_jLblPleaseWait, 0,
                frameHeight / 12 - frameHeight / 72,
                frameWidth - frameWidth / 32, frameHeight / 12);

        //gameHost
        changeBound(gameHost_jLblCall, 0,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_jLblRefill, frameHeight / 12 / 2 + frameHeight / 12 * 4 - frameHeight / 36,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_jLblRefillNumber, frameHeight / 12 / 2 + frameHeight / 12 * 5,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_jLblGameName, (frameWidth / 2 - frameHeight / 12 * 6 / 2 - frameWidth / 64) * -1,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36,
                frameHeight / 12 * 6, frameHeight / 12);
        changeBound(gameHost_jLblGroup, frameHeight / 12 + frameHeight / 36,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_jLblHalf, (frameHeight / 12 + frameHeight / 36) * -1,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_jLblPlayerName, (frameWidth / 2 - frameHeight / 12 * 6 / 2 - frameWidth / 64) * -1,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12 * 6, frameHeight / 12);
        changeBound(gameHost_jLblPoint, 0,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36,
                frameHeight / 12 * 3 + frameHeight / 36 * 2, frameHeight / 12);
        changeBound(gameHost_jLblQuestion, 0,
                frameHeight / 2 - frameHeight / 4 / 2 - frameHeight / 36 * 2 - frameHeight / 12 * 2 - frameHeight / 36,
                frameWidth - frameWidth / 32, frameHeight / 4);
        changeBound(gameHost_jLblCup, frameHeight / 12 / 2 + frameHeight / 12 * 4 - frameHeight / 36,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_jLblCupNumber, frameHeight / 12 / 2 + frameHeight / 12 * 5,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12, frameHeight / 12);
        changeBound(gameHost_kBttnNextQuestion, frameWidth / 2 - frameHeight / 12 * 4 / 2 - frameWidth / 64,
                (frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36) * -1,
                frameHeight / 12 * 4, frameHeight / 12);
        changeBound(gameHost_kBttnRefill, frameWidth / 2 - frameHeight / 12 * 4 / 2 - frameWidth / 64,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36,
                frameHeight / 12 * 4, frameHeight / 12);
        changeBound(gameHost_kBttnShowAnswer, 0,
                (frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36) * -1,
                frameHeight / 12 * 4, frameHeight / 12);
        changeBound(gameHost_kBttnEndPlayerGame, frameWidth / 2 - frameHeight / 12 * 4 / 2 - frameWidth / 64,
                frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36 * 2 - frameHeight / 12,
                frameHeight / 12 * 4, frameHeight / 12);

        //exit
        changeBound(exit_JLblLogo, 0,
                frameHeight / 2 - frameHeight / 3 / 2 - frameHeight / 36,
                frameWidth - frameWidth / 32, frameHeight / 3);
        changeBound(exit_kBttnEndGame, 0,
                (frameHeight / 24) * -1,
                frameHeight / 12 * 4, frameHeight / 12);
        changeBound(exit_kBttnExit, frameWidth / 2 - frameHeight / 12 * 4 / 2 - frameWidth / 64,
                (frameHeight / 2 - frameHeight / 12 / 2 - frameHeight / 36) * -1,
                frameHeight / 12 * 4, frameHeight / 12);
        changeBound(exit_kBttnNewGame, 0,
                frameHeight / 12 - frameHeight / 72,
                frameHeight / 12 * 4, frameHeight / 12);
    }

    ///SAJÁT ELJÁRÁSOK VÉGE
    ///EVENTEK
    public void receive_PlayerGameStarted() {
        displayNewQuestion();
        revealAnswerPanelColor(gameHost_kGrdntPnl);
    }

    public void receive_AnswerCupsChanged() {
        int index = 0;
        cupsLeft = gameHandlerInstance.getActualPlayer().getCupsLeft();
        for (Component cmp : gameHost_kGrdntPnl.getComponents()) {
            if (cmp.getClass() == new KGradientPanel().getClass()) {
                KGradientPanel panel = (KGradientPanel) cmp;
                ((JLabel) panel.getComponent(1)).setText(gameHandlerInstance.getPickedAnswersAsCups()[index]);
                cupsLeft -= Integer.parseInt(((JLabel) panel.getComponent(1)).getText());
                index++;
            }
        }
        gameHost_jLblCupNumber.setText(cupsLeft + "/" + gameHandlerInstance.getActualPlayer().getCupsLeft());
    }

    public void receive_HalfHelpUsed(List<Integer> indexesToRemove) {
        turnOffSpecifiecAnswerPanels(gameHost_kGrdntPnl, indexesToRemove);
        gameHost_jLblHalf.setEnabled(false);
    }

    public void receive_CallHelpUsed() {
        gameHost_jLblCall.setEnabled(false);
    }

    public void receive_GroupHelpUsed() {
        gameHost_jLblGroup.setEnabled(false);
    }

    ///EVENTEK VÉGE
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jFrameHostInstance = new JFrameHost();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit_JLblLogo;
    private com.k33ptoo.components.KButton exit_kBttnEndGame;
    private com.k33ptoo.components.KButton exit_kBttnExit;
    private com.k33ptoo.components.KButton exit_kBttnNewGame;
    private com.k33ptoo.components.KGradientPanel exit_kGrdntPnl;
    private javax.swing.JLabel gameHost_jLblCall;
    private javax.swing.JLabel gameHost_jLblCup;
    private javax.swing.JLabel gameHost_jLblCupNumber;
    private javax.swing.JLabel gameHost_jLblGameName;
    private javax.swing.JLabel gameHost_jLblGroup;
    private javax.swing.JLabel gameHost_jLblHalf;
    private javax.swing.JLabel gameHost_jLblPlayerName;
    private javax.swing.JLabel gameHost_jLblPoint;
    private javax.swing.JLabel gameHost_jLblQuestion;
    private javax.swing.JLabel gameHost_jLblRefill;
    private javax.swing.JLabel gameHost_jLblRefillNumber;
    private com.k33ptoo.components.KButton gameHost_kBttnEndPlayerGame;
    private com.k33ptoo.components.KButton gameHost_kBttnNextQuestion;
    private com.k33ptoo.components.KButton gameHost_kBttnRefill;
    private com.k33ptoo.components.KButton gameHost_kBttnShowAnswer;
    private com.k33ptoo.components.KGradientPanel gameHost_kGrdntPnl;
    private javax.swing.JLayeredPane jLyrdPn;
    private javax.swing.JLabel waitingScreen_JLblLogo;
    private javax.swing.JLabel waitingScreen_jLblPleaseWait;
    private com.k33ptoo.components.KGradientPanel waitingScreen_kGrdntPnl;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void addCups(JLabel label, int index) {
    }

    @Override
    protected void subtractCups(JLabel label, int index) {
    }
}
