/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Jani
 */
public class JFramePlayer extends javax.swing.JFrame {

    int frameHeight, frameWidth;

    /**
     * Creates new form JFramePlayer
     */
    public JFramePlayer() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        showOnScreen(2, this);

        endGame_kGrdntPnl.setVisible(false);
        game_kGrdntPnl.setVisible(false);
        scores_kGrdntPnl.setVisible(false);

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        frameWidth = dimension.width;
        frameHeight = dimension.height;

        setPreferredSize(dimension);
        newPlayer_kGrdntPnl.setSize(dimension);
        newPlayer_jTxtFldPlayerName.setBounds(frameHeight / 2, frameWidth / 2, 300, 50);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLyrdPn = new javax.swing.JLayeredPane();
        newPlayer_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        newPlayer_jTxtFldPlayerName = new javax.swing.JTextField();
        newPlayer_kBttnStart = new com.k33ptoo.components.KButton();
        game_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        endGame_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        scores_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        newPlayer_jTxtFldPlayerName.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newPlayer_jTxtFldPlayerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newPlayer_jTxtFldPlayerName.setText("Add meg a játék nevét!");
        newPlayer_jTxtFldPlayerName.setPreferredSize(new java.awt.Dimension(300, 50));

        newPlayer_kBttnStart.setBorder(null);
        newPlayer_kBttnStart.setText("Játék indítása");
        newPlayer_kBttnStart.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newPlayer_kBttnStart.setkBorderRadius(50);
        newPlayer_kBttnStart.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout newPlayer_kGrdntPnlLayout = new javax.swing.GroupLayout(newPlayer_kGrdntPnl);
        newPlayer_kGrdntPnl.setLayout(newPlayer_kGrdntPnlLayout);
        newPlayer_kGrdntPnlLayout.setHorizontalGroup(
            newPlayer_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                .addGroup(newPlayer_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(newPlayer_jTxtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(newPlayer_kBttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        newPlayer_kGrdntPnlLayout.setVerticalGroup(
            newPlayer_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(newPlayer_jTxtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(newPlayer_kBttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout game_kGrdntPnlLayout = new javax.swing.GroupLayout(game_kGrdntPnl);
        game_kGrdntPnl.setLayout(game_kGrdntPnlLayout);
        game_kGrdntPnlLayout.setHorizontalGroup(
            game_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        game_kGrdntPnlLayout.setVerticalGroup(
            game_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout endGame_kGrdntPnlLayout = new javax.swing.GroupLayout(endGame_kGrdntPnl);
        endGame_kGrdntPnl.setLayout(endGame_kGrdntPnlLayout);
        endGame_kGrdntPnlLayout.setHorizontalGroup(
            endGame_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        endGame_kGrdntPnlLayout.setVerticalGroup(
            endGame_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout scores_kGrdntPnlLayout = new javax.swing.GroupLayout(scores_kGrdntPnl);
        scores_kGrdntPnl.setLayout(scores_kGrdntPnlLayout);
        scores_kGrdntPnlLayout.setHorizontalGroup(
            scores_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        scores_kGrdntPnlLayout.setVerticalGroup(
            scores_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLyrdPn.setLayer(newPlayer_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(game_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(endGame_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(scores_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLyrdPnLayout = new javax.swing.GroupLayout(jLyrdPn);
        jLyrdPn.setLayout(jLyrdPnLayout);
        jLyrdPnLayout.setHorizontalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newPlayer_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(game_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(endGame_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scores_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLyrdPnLayout.setVerticalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newPlayer_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(game_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(endGame_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scores_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLyrdPn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLyrdPn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePlayer().setVisible(true);
            }
        });
    }

    public static void showOnScreen(int screen, JFrame frame) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gd = ge.getScreenDevices();

        if (screen > -1 && screen < gd.length) {
            //gd[screen].setFullScreenWindow(frame);
            frame.setLocation(gd[screen].getDefaultConfiguration().getBounds().x, frame.getY());
        } else if (gd.length > 0) {
            //gd[0].setFullScreenWindow(frame);
            frame.setLocation(gd[0].getDefaultConfiguration().getBounds().x, frame.getY());
        } else {
            throw new RuntimeException("No screen found!");

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel endGame_kGrdntPnl;
    private com.k33ptoo.components.KGradientPanel game_kGrdntPnl;
    private javax.swing.JLayeredPane jLyrdPn;
    private javax.swing.JTextField newPlayer_jTxtFldPlayerName;
    private com.k33ptoo.components.KButton newPlayer_kBttnStart;
    private com.k33ptoo.components.KGradientPanel newPlayer_kGrdntPnl;
    private com.k33ptoo.components.KGradientPanel scores_kGrdntPnl;
    // End of variables declaration//GEN-END:variables
}
