/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.*;
import Helpers.GameGenerator;
import Helpers.GameHandler;
import Helpers.DatabaseHandler;
import Models.Game;
import Models.Question;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

/**
 *
 * @author Jani
 */
public class JFrameTestHost extends javax.swing.JFrame {

    Game game;
    GameGenerator gameGenerator;
    GameHandler gameHandler;
    DatabaseHandler databaseHandler;
    /**
     * Creates new form JFrameTestHost
     */
    ImageIcon icon = new ImageIcon(".//resources/images/icon.png");

    public JFrameTestHost() {
        initComponents();

        gameGenerator = new GameGenerator();
        databaseHandler = new DatabaseHandler();

        settings_kGrdntPnl.setVisible(false);
        newGame_kGrdntPnlSources.setVisible(false);
        newGame_kGrdntPnlCategories.setVisible(false);
        newGame_kGrdntPnlGameName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLyrdPn = new javax.swing.JLayeredPane();
        menu_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        menu_bttnExit = new com.k33ptoo.components.KButton();
        menu_bttnSettings = new com.k33ptoo.components.KButton();
        menu_bttnLoadGame = new com.k33ptoo.components.KButton();
        menu_bttnNewGame = new com.k33ptoo.components.KButton();
        menu_JLblLogo = new javax.swing.JLabel();
        settings_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        settings_kBttnBack = new com.k33ptoo.components.KButton();
        settings_kBttnImportQuizzes = new com.k33ptoo.components.KButton();
        settings_jLblImportQuizzes = new javax.swing.JLabel();
        settings_kBttnImportQuizzesFromNapiKviz = new com.k33ptoo.components.KButton();
        settings_jLblImportQuizzesFromNapiKviz = new javax.swing.JLabel();
        settings_kBttnClearQuestion = new com.k33ptoo.components.KButton();
        settings_jLblClearQuestion = new javax.swing.JLabel();
        settings_kBttnClearGames = new com.k33ptoo.components.KButton();
        settings_jLblClearGames = new javax.swing.JLabel();
        settings_JLblLogo = new javax.swing.JLabel();
        newGame_jLyrdPn = new javax.swing.JLayeredPane();
        newGame_kGrdntPnlSources = new com.k33ptoo.components.KGradientPanel();
        newGame_Sources_kBttnBack = new com.k33ptoo.components.KButton();
        newGame_Sources_kBttnNext = new com.k33ptoo.components.KButton();
        newGame_Sources_JLblLogo = new javax.swing.JLabel();
        newGame_kGrdntPnlCategories = new com.k33ptoo.components.KGradientPanel();
        newGame_Categories_kBttnBack = new com.k33ptoo.components.KButton();
        newGame_Categories_kBttnNext = new com.k33ptoo.components.KButton();
        newGame_Categories_JLblLogo = new javax.swing.JLabel();
        newGame_kGrdntPnlGameName = new com.k33ptoo.components.KGradientPanel();
        newGame_GameName_kBttnStart = new com.k33ptoo.components.KButton();
        newGame_GameName_kBttnBack = new com.k33ptoo.components.KButton();
        newGame_GameName_jTxtFldGameName = new javax.swing.JTextField();
        newGame_GameName_JLblLogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setIconImage(icon.getImage());
        setName("frame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        menu_kGrdntPnl.setkEndColor(new java.awt.Color(44, 7, 53));
        menu_kGrdntPnl.setkStartColor(new java.awt.Color(78, 20, 140));

        menu_bttnExit.setBorder(null);
        menu_bttnExit.setText("Exit");
        menu_bttnExit.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        menu_bttnExit.setkBorderRadius(50);
        menu_bttnExit.setPreferredSize(new java.awt.Dimension(200, 50));
        menu_bttnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_bttnExitMouseClicked(evt);
            }
        });

        menu_bttnSettings.setBorder(null);
        menu_bttnSettings.setText("Settings");
        menu_bttnSettings.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        menu_bttnSettings.setkBorderRadius(50);
        menu_bttnSettings.setPreferredSize(new java.awt.Dimension(200, 50));
        menu_bttnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_bttnSettingsMouseClicked(evt);
            }
        });

        menu_bttnLoadGame.setBorder(null);
        menu_bttnLoadGame.setText("Load Game");
        menu_bttnLoadGame.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        menu_bttnLoadGame.setkBorderRadius(50);
        menu_bttnLoadGame.setPreferredSize(new java.awt.Dimension(200, 50));

        menu_bttnNewGame.setBorder(null);
        menu_bttnNewGame.setText("New Game");
        menu_bttnNewGame.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        menu_bttnNewGame.setkBorderRadius(50);
        menu_bttnNewGame.setPreferredSize(new java.awt.Dimension(200, 50));
        menu_bttnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_bttnNewGameMouseClicked(evt);
            }
        });

        menu_JLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_JLblLogo.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        javax.swing.GroupLayout menu_kGrdntPnlLayout = new javax.swing.GroupLayout(menu_kGrdntPnl);
        menu_kGrdntPnl.setLayout(menu_kGrdntPnlLayout);
        menu_kGrdntPnlLayout.setHorizontalGroup(
            menu_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_kGrdntPnlLayout.createSequentialGroup()
                .addGroup(menu_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(298, 594, Short.MAX_VALUE)
                        .addComponent(menu_bttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(menu_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu_bttnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_bttnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_bttnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menu_kGrdntPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu_JLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menu_kGrdntPnlLayout.setVerticalGroup(
            menu_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_kGrdntPnlLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(menu_JLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_bttnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_bttnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_bttnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(menu_bttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        settings_kGrdntPnl.setkEndColor(new java.awt.Color(44, 7, 53));
        settings_kGrdntPnl.setkStartColor(new java.awt.Color(78, 20, 140));
        settings_kGrdntPnl.setkTransparentControls(false);

        settings_kBttnBack.setBorder(null);
        settings_kBttnBack.setText("Vissza");
        settings_kBttnBack.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_kBttnBack.setkBorderRadius(50);
        settings_kBttnBack.setPreferredSize(new java.awt.Dimension(200, 50));
        settings_kBttnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_kBttnBackMouseClicked(evt);
            }
        });

        settings_kBttnImportQuizzes.setBorder(null);
        settings_kBttnImportQuizzes.setText("Importálás");
        settings_kBttnImportQuizzes.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_kBttnImportQuizzes.setkBorderRadius(50);
        settings_kBttnImportQuizzes.setPreferredSize(new java.awt.Dimension(200, 50));
        settings_kBttnImportQuizzes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_kBttnImportQuizzesMouseClicked(evt);
            }
        });

        settings_jLblImportQuizzes.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_jLblImportQuizzes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        settings_jLblImportQuizzes.setText("Kvízek importálása a webhelyekről:");
        settings_jLblImportQuizzes.setPreferredSize(new java.awt.Dimension(350, 50));

        settings_kBttnImportQuizzesFromNapiKviz.setBorder(null);
        settings_kBttnImportQuizzesFromNapiKviz.setText("NapiKvíz");
        settings_kBttnImportQuizzesFromNapiKviz.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_kBttnImportQuizzesFromNapiKviz.setkBorderRadius(50);
        settings_kBttnImportQuizzesFromNapiKviz.setPreferredSize(new java.awt.Dimension(200, 50));
        settings_kBttnImportQuizzesFromNapiKviz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_kBttnImportQuizzesFromNapiKvizMouseClicked(evt);
            }
        });

        settings_jLblImportQuizzesFromNapiKviz.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_jLblImportQuizzesFromNapiKviz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        settings_jLblImportQuizzesFromNapiKviz.setText("Kvízek importálása NapiKvízről:");
        settings_jLblImportQuizzesFromNapiKviz.setPreferredSize(new java.awt.Dimension(350, 50));

        settings_kBttnClearQuestion.setBorder(null);
        settings_kBttnClearQuestion.setText("Kvízek törlése");
        settings_kBttnClearQuestion.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_kBttnClearQuestion.setkBorderRadius(50);
        settings_kBttnClearQuestion.setPreferredSize(new java.awt.Dimension(200, 50));
        settings_kBttnClearQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_kBttnClearQuestionMouseClicked(evt);
            }
        });

        settings_jLblClearQuestion.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_jLblClearQuestion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        settings_jLblClearQuestion.setText("Minden kvíz törlése az adatbázisból:");
        settings_jLblClearQuestion.setPreferredSize(new java.awt.Dimension(350, 50));

        settings_kBttnClearGames.setBorder(null);
        settings_kBttnClearGames.setText("Játékok törlése");
        settings_kBttnClearGames.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_kBttnClearGames.setkBorderRadius(50);
        settings_kBttnClearGames.setPreferredSize(new java.awt.Dimension(200, 50));
        settings_kBttnClearGames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_kBttnClearGamesMouseClicked(evt);
            }
        });

        settings_jLblClearGames.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settings_jLblClearGames.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        settings_jLblClearGames.setText("Eddigi játékok törlése:");
        settings_jLblClearGames.setPreferredSize(new java.awt.Dimension(350, 50));

        settings_JLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings_JLblLogo.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        javax.swing.GroupLayout settings_kGrdntPnlLayout = new javax.swing.GroupLayout(settings_kGrdntPnl);
        settings_kGrdntPnl.setLayout(settings_kGrdntPnlLayout);
        settings_kGrdntPnlLayout.setHorizontalGroup(
            settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settings_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settings_kGrdntPnlLayout.createSequentialGroup()
                        .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settings_jLblClearQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settings_jLblImportQuizzesFromNapiKviz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settings_jLblImportQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settings_jLblClearGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settings_kBttnClearGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settings_kBttnImportQuizzesFromNapiKviz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settings_kBttnImportQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settings_kBttnClearQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settings_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(settings_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(settings_JLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        settings_kGrdntPnlLayout.setVerticalGroup(
            settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settings_kGrdntPnlLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(settings_JLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_kBttnImportQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_jLblImportQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_kBttnImportQuizzesFromNapiKviz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_jLblImportQuizzesFromNapiKviz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_kBttnClearQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_jLblClearQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(settings_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_jLblClearGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_kBttnClearGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(settings_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        newGame_kGrdntPnlSources.setkEndColor(new java.awt.Color(44, 7, 53));
        newGame_kGrdntPnlSources.setkStartColor(new java.awt.Color(78, 20, 140));

        newGame_Sources_kBttnBack.setBorder(null);
        newGame_Sources_kBttnBack.setText("Vissza");
        newGame_Sources_kBttnBack.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_Sources_kBttnBack.setkBorderRadius(50);
        newGame_Sources_kBttnBack.setPreferredSize(new java.awt.Dimension(200, 50));
        newGame_Sources_kBttnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_Sources_kBttnBackMouseClicked(evt);
            }
        });

        newGame_Sources_kBttnNext.setBorder(null);
        newGame_Sources_kBttnNext.setText("Következő");
        newGame_Sources_kBttnNext.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_Sources_kBttnNext.setkBorderRadius(50);
        newGame_Sources_kBttnNext.setPreferredSize(new java.awt.Dimension(200, 50));
        newGame_Sources_kBttnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_Sources_kBttnNextMouseClicked(evt);
            }
        });

        newGame_Sources_JLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGame_Sources_JLblLogo.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        javax.swing.GroupLayout newGame_kGrdntPnlSourcesLayout = new javax.swing.GroupLayout(newGame_kGrdntPnlSources);
        newGame_kGrdntPnlSources.setLayout(newGame_kGrdntPnlSourcesLayout);
        newGame_kGrdntPnlSourcesLayout.setHorizontalGroup(
            newGame_kGrdntPnlSourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGame_kGrdntPnlSourcesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newGame_kGrdntPnlSourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGame_kGrdntPnlSourcesLayout.createSequentialGroup()
                        .addGap(0, 370, Short.MAX_VALUE)
                        .addComponent(newGame_Sources_kBttnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newGame_Sources_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newGame_Sources_JLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        newGame_kGrdntPnlSourcesLayout.setVerticalGroup(
            newGame_kGrdntPnlSourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGame_kGrdntPnlSourcesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(newGame_Sources_JLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addGroup(newGame_kGrdntPnlSourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGame_Sources_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGame_Sources_kBttnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        newGame_kGrdntPnlCategories.setkEndColor(new java.awt.Color(44, 7, 53));
        newGame_kGrdntPnlCategories.setkStartColor(new java.awt.Color(78, 20, 140));

        newGame_Categories_kBttnBack.setBorder(null);
        newGame_Categories_kBttnBack.setText("Vissza");
        newGame_Categories_kBttnBack.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_Categories_kBttnBack.setkBorderRadius(50);
        newGame_Categories_kBttnBack.setPreferredSize(new java.awt.Dimension(200, 50));
        newGame_Categories_kBttnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_Categories_kBttnBackMouseClicked(evt);
            }
        });

        newGame_Categories_kBttnNext.setBorder(null);
        newGame_Categories_kBttnNext.setText("Következő");
        newGame_Categories_kBttnNext.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_Categories_kBttnNext.setkBorderRadius(50);
        newGame_Categories_kBttnNext.setPreferredSize(new java.awt.Dimension(200, 50));
        newGame_Categories_kBttnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_Categories_kBttnNextMouseClicked(evt);
            }
        });

        newGame_Categories_JLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGame_Categories_JLblLogo.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        javax.swing.GroupLayout newGame_kGrdntPnlCategoriesLayout = new javax.swing.GroupLayout(newGame_kGrdntPnlCategories);
        newGame_kGrdntPnlCategories.setLayout(newGame_kGrdntPnlCategoriesLayout);
        newGame_kGrdntPnlCategoriesLayout.setHorizontalGroup(
            newGame_kGrdntPnlCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGame_kGrdntPnlCategoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newGame_kGrdntPnlCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGame_kGrdntPnlCategoriesLayout.createSequentialGroup()
                        .addGap(0, 370, Short.MAX_VALUE)
                        .addComponent(newGame_Categories_kBttnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newGame_Categories_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newGame_Categories_JLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        newGame_kGrdntPnlCategoriesLayout.setVerticalGroup(
            newGame_kGrdntPnlCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGame_kGrdntPnlCategoriesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(newGame_Categories_JLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addGroup(newGame_kGrdntPnlCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGame_Categories_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGame_Categories_kBttnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        newGame_kGrdntPnlGameName.setkEndColor(new java.awt.Color(44, 7, 53));
        newGame_kGrdntPnlGameName.setkStartColor(new java.awt.Color(78, 20, 140));

        newGame_GameName_kBttnStart.setBorder(null);
        newGame_GameName_kBttnStart.setText("Játék indítás");
        newGame_GameName_kBttnStart.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_GameName_kBttnStart.setkBorderRadius(50);
        newGame_GameName_kBttnStart.setPreferredSize(new java.awt.Dimension(200, 50));
        newGame_GameName_kBttnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_GameName_kBttnStartMouseClicked(evt);
            }
        });

        newGame_GameName_kBttnBack.setBorder(null);
        newGame_GameName_kBttnBack.setText("Vissza");
        newGame_GameName_kBttnBack.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_GameName_kBttnBack.setkBorderRadius(50);
        newGame_GameName_kBttnBack.setPreferredSize(new java.awt.Dimension(200, 50));
        newGame_GameName_kBttnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_GameName_kBttnBackMouseClicked(evt);
            }
        });

        newGame_GameName_jTxtFldGameName.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newGame_GameName_jTxtFldGameName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newGame_GameName_jTxtFldGameName.setText("Add meg a játék nevét!");
        newGame_GameName_jTxtFldGameName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        newGame_GameName_jTxtFldGameName.setPreferredSize(new java.awt.Dimension(300, 50));
        newGame_GameName_jTxtFldGameName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGame_GameName_jTxtFldGameNameMouseClicked(evt);
            }
        });

        newGame_GameName_JLblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGame_GameName_JLblLogo1.setIcon(new ImageIcon("resources/images/DrinQuiz.gif"));

        javax.swing.GroupLayout newGame_kGrdntPnlGameNameLayout = new javax.swing.GroupLayout(newGame_kGrdntPnlGameName);
        newGame_kGrdntPnlGameName.setLayout(newGame_kGrdntPnlGameNameLayout);
        newGame_kGrdntPnlGameNameLayout.setHorizontalGroup(
            newGame_kGrdntPnlGameNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGame_kGrdntPnlGameNameLayout.createSequentialGroup()
                .addGroup(newGame_kGrdntPnlGameNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newGame_kGrdntPnlGameNameLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(newGame_GameName_kBttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(newGame_kGrdntPnlGameNameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newGame_kGrdntPnlGameNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newGame_kGrdntPnlGameNameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(newGame_GameName_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newGame_GameName_JLblLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(newGame_kGrdntPnlGameNameLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(newGame_GameName_jTxtFldGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        newGame_kGrdntPnlGameNameLayout.setVerticalGroup(
            newGame_kGrdntPnlGameNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGame_kGrdntPnlGameNameLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(newGame_GameName_JLblLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(newGame_GameName_jTxtFldGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newGame_GameName_kBttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(newGame_GameName_kBttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        newGame_jLyrdPn.setLayer(newGame_kGrdntPnlSources, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newGame_jLyrdPn.setLayer(newGame_kGrdntPnlCategories, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newGame_jLyrdPn.setLayer(newGame_kGrdntPnlGameName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout newGame_jLyrdPnLayout = new javax.swing.GroupLayout(newGame_jLyrdPn);
        newGame_jLyrdPn.setLayout(newGame_jLyrdPnLayout);
        newGame_jLyrdPnLayout.setHorizontalGroup(
            newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_kGrdntPnlSources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_kGrdntPnlCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_kGrdntPnlGameName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newGame_jLyrdPnLayout.setVerticalGroup(
            newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_kGrdntPnlSources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_kGrdntPnlCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newGame_jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_kGrdntPnlGameName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLyrdPn.setLayer(menu_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(settings_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(newGame_jLyrdPn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLyrdPnLayout = new javax.swing.GroupLayout(jLyrdPn);
        jLyrdPn.setLayout(jLyrdPnLayout);
        jLyrdPnLayout.setHorizontalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_kGrdntPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(settings_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_jLyrdPn))
        );
        jLyrdPnLayout.setVerticalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_kGrdntPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(settings_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newGame_jLyrdPn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLyrdPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLyrdPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_bttnNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bttnNewGameMouseClicked
        // TODO add your handling code here:
        menu_kGrdntPnl.setVisible(false);

        addSourceCheckboxesToPanel();

        newGame_kGrdntPnlSources.setVisible(true);
    }//GEN-LAST:event_menu_bttnNewGameMouseClicked

    private void menu_bttnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bttnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_bttnExitMouseClicked

    private void newGame_Sources_kBttnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_Sources_kBttnBackMouseClicked
        // TODO add your handling code here:
        newGame_kGrdntPnlSources.setVisible(false);
        menu_kGrdntPnl.setVisible(true);
    }//GEN-LAST:event_newGame_Sources_kBttnBackMouseClicked

    private void newGame_Categories_kBttnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_Categories_kBttnBackMouseClicked
        // TODO add your handling code here:
        newGame_kGrdntPnlCategories.setVisible(false);
        newGame_kGrdntPnlSources.setVisible(true);
    }//GEN-LAST:event_newGame_Categories_kBttnBackMouseClicked

    private void newGame_Categories_kBttnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_Categories_kBttnNextMouseClicked
        // TODO add your handling code here:
        gameGenerator.setChosenCategories(chosenCategoriesToStringArray());

        newGame_kGrdntPnlCategories.setVisible(false);
        newGame_kGrdntPnlGameName.setVisible(true);

    }//GEN-LAST:event_newGame_Categories_kBttnNextMouseClicked

    private void newGame_GameName_kBttnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_GameName_kBttnStartMouseClicked
        // TODO add your handling code here:
        gameGenerator.generateGame(newGame_GameName_jTxtFldGameName.getText());
        game = gameGenerator.getGame();
        gameHandler = new GameHandler(game);

        newGame_kGrdntPnlGameName.setVisible(false);
        //MODIFY LATER THE MENU SELECTION TO GAME
        menu_kGrdntPnl.setVisible(true);
    }//GEN-LAST:event_newGame_GameName_kBttnStartMouseClicked

    private void newGame_GameName_kBttnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_GameName_kBttnBackMouseClicked
        // TODO add your handling code here:
        newGame_kGrdntPnlGameName.setVisible(false);
        newGame_kGrdntPnlCategories.setVisible(true);
    }//GEN-LAST:event_newGame_GameName_kBttnBackMouseClicked

    private void newGame_Sources_kBttnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_Sources_kBttnNextMouseClicked
        // TODO add your handling code here:
        gameGenerator.setChosenSources(chosenSourcesToStringArray());
        newGame_kGrdntPnlSources.setVisible(false);

        addCategoryCheckboxesToPanel();

        newGame_kGrdntPnlCategories.setVisible(true);
    }//GEN-LAST:event_newGame_Sources_kBttnNextMouseClicked

    private void settings_kBttnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_kBttnBackMouseClicked
        // TODO add your handling code here:
        settings_kGrdntPnl.setVisible(false);
        menu_kGrdntPnl.setVisible(true);
    }//GEN-LAST:event_settings_kBttnBackMouseClicked

    private void menu_bttnSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bttnSettingsMouseClicked
        // TODO add your handling code here:
        menu_kGrdntPnl.setVisible(false);
        settings_kGrdntPnl.setVisible(true);
    }//GEN-LAST:event_menu_bttnSettingsMouseClicked

    private void settings_kBttnImportQuizzesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_kBttnImportQuizzesMouseClicked
        try {
            // TODO add your handling code here:
            databaseHandler.importAllKvizToDatabase();
        } catch (IOException ex) {
            Logger.getLogger(JFrameTestHost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_settings_kBttnImportQuizzesMouseClicked

    private void settings_kBttnImportQuizzesFromNapiKvizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_kBttnImportQuizzesFromNapiKvizMouseClicked
        try {
            // TODO add your handling code here:
            databaseHandler.importNapikvizToDatabase();
        } catch (IOException ex) {
            Logger.getLogger(JFrameTestHost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_settings_kBttnImportQuizzesFromNapiKvizMouseClicked

    private void settings_kBttnClearQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_kBttnClearQuestionMouseClicked
        // TODO add your handling code here:
        databaseHandler.clearQuestionsInDatabase();
    }//GEN-LAST:event_settings_kBttnClearQuestionMouseClicked

    private void settings_kBttnClearGamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_kBttnClearGamesMouseClicked
        // TODO add your handling code here:
        databaseHandler.clearGamesInDatabase();
    }//GEN-LAST:event_settings_kBttnClearGamesMouseClicked

    private void newGame_GameName_jTxtFldGameNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGame_GameName_jTxtFldGameNameMouseClicked
        // TODO add your handling code here:
        if (newGame_GameName_jTxtFldGameName.getText().equals("Add meg a játék nevét!")) {
            newGame_GameName_jTxtFldGameName.setText("");
        }
    }//GEN-LAST:event_newGame_GameName_jTxtFldGameNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestHost().setVisible(true);
            }
        });
    }

    ///SAJÁT ELJÁRÁSOK
    private void addSourceCheckboxesToPanel() {
        String[] sources = gameGenerator.getSourcesInDatabase();

        javax.swing.JCheckBox[] jCheckboxArray;
        int CheckBoxNumber = sources.length;
        jCheckboxArray = new javax.swing.JCheckBox[CheckBoxNumber];
        for (int x = 0; x < CheckBoxNumber; x++) {
            jCheckboxArray[x] = new javax.swing.JCheckBox();
            jCheckboxArray[x].setText(sources[x]);
            jCheckboxArray[x].setBounds(20, x * 50, 300, 30);
            jCheckboxArray[x].doClick();
            newGame_kGrdntPnlSources.add(jCheckboxArray[x]);
        }
    }

    private void addCategoryCheckboxesToPanel() {
        String[] categories = gameGenerator.getCategoriesBySourcesInDatabase();

        javax.swing.JCheckBox[] jCheckboxArray;
        int CheckBoxNumber = categories.length;
        jCheckboxArray = new javax.swing.JCheckBox[CheckBoxNumber];
        for (int x = 0; x < CheckBoxNumber; x++) {
            jCheckboxArray[x] = new javax.swing.JCheckBox();
            jCheckboxArray[x].setText(categories[x]);
            jCheckboxArray[x].setBounds(20, x * 50, 300, 30);
            jCheckboxArray[x].doClick();
            newGame_kGrdntPnlCategories.add(jCheckboxArray[x]);
        }
    }

    private String[] chosenSourcesToStringArray() {
        String[] choosenSources;
        JCheckBox tryIt = new JCheckBox();

        List<JCheckBox> jCheckboxArray = new ArrayList<>();

        for (Component box : newGame_kGrdntPnlSources.getComponents()) {
            if (box.getClass() == tryIt.getClass()) {
                jCheckboxArray.add((JCheckBox) box);
                if (!jCheckboxArray.get(jCheckboxArray.size() - 1).isSelected()) {
                    jCheckboxArray.remove(jCheckboxArray.size() - 1);
                }
            }
        }

        choosenSources = new String[jCheckboxArray.size()];
        for (int i = 0; i < jCheckboxArray.size(); ++i) {
            choosenSources[i] = jCheckboxArray.get(i).getText();
        }

//        for(String s : choosenSources)
//        {
//            System.out.println(s);
//        }
        return choosenSources;
    }

    private String[] chosenCategoriesToStringArray() {
        String[] choosenCategories;
        JCheckBox tryIt = new JCheckBox();

        List<JCheckBox> jCheckboxArray = new ArrayList<>();

        for (Component box : newGame_kGrdntPnlCategories.getComponents()) {
            if (box.getClass() == tryIt.getClass()) {
                jCheckboxArray.add((JCheckBox) box);
                if (!jCheckboxArray.get(jCheckboxArray.size() - 1).isSelected()) {
                    jCheckboxArray.remove(jCheckboxArray.size() - 1);
                }
            }
        }

        choosenCategories = new String[jCheckboxArray.size()];
        for (int i = 0; i < jCheckboxArray.size(); ++i) {
            choosenCategories[i] = jCheckboxArray.get(i).getText();
        }

//        for(String s : choosenCategories)
//        {
//            System.out.println(s);
//        }
        return choosenCategories;
    }
    ///SAJÁT ELJÁRÁSOK VÉGE

//    private String chosenSourcesToString() {
//        String str = "";
//        JCheckBox tryIt = new JCheckBox();
//
//        List<JCheckBox> jCheckboxArray = new ArrayList<>();
//
//        for (Component box : newGame_kGrdntPnlSources.getComponents()) {
//            if (box.getClass() == tryIt.getClass()) {
//                jCheckboxArray.add((JCheckBox) box);
//                if (!jCheckboxArray.get(jCheckboxArray.size() - 1).isSelected()) {
//                    jCheckboxArray.remove(jCheckboxArray.size() - 1);
//                }
//            }
//        }
//
//        str += jCheckboxArray.get(0).getText();
//        for (int i = 1; i < jCheckboxArray.size(); ++i) {
//            str += ";;SEP;;";
//            str += jCheckboxArray.get(i).getText();
//        }
//        System.out.println(str);
//        return str;
//    }
//    private String chosenCategoriesToString() {
//        String str = "";
//        JCheckBox tryIt = new JCheckBox();
//
//        List<JCheckBox> jCheckboxArray = new ArrayList<>();
//
//        for (Component box : newGame_kGrdntPnlCategories.getComponents()) {
//            if (box.getClass() == tryIt.getClass()) {
//                jCheckboxArray.add((JCheckBox) box);
//                if (!jCheckboxArray.get(jCheckboxArray.size() - 1).isSelected()) {
//                    jCheckboxArray.remove(jCheckboxArray.size() - 1);
//                }
//            }
//        }
//
//        str += jCheckboxArray.get(0).getText();
//        for (int i = 1; i < jCheckboxArray.size(); ++i) {
//            str += ";;SEP;;";
//            str += jCheckboxArray.get(i).getText();
//        }
//        System.out.println(str);
//        return str;
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLyrdPn;
    private javax.swing.JLabel menu_JLblLogo;
    private com.k33ptoo.components.KButton menu_bttnExit;
    private com.k33ptoo.components.KButton menu_bttnLoadGame;
    public com.k33ptoo.components.KButton menu_bttnNewGame;
    private com.k33ptoo.components.KButton menu_bttnSettings;
    private com.k33ptoo.components.KGradientPanel menu_kGrdntPnl;
    private javax.swing.JLabel newGame_Categories_JLblLogo;
    private com.k33ptoo.components.KButton newGame_Categories_kBttnBack;
    private com.k33ptoo.components.KButton newGame_Categories_kBttnNext;
    private javax.swing.JLabel newGame_GameName_JLblLogo1;
    private javax.swing.JTextField newGame_GameName_jTxtFldGameName;
    private com.k33ptoo.components.KButton newGame_GameName_kBttnBack;
    private com.k33ptoo.components.KButton newGame_GameName_kBttnStart;
    private javax.swing.JLabel newGame_Sources_JLblLogo;
    private com.k33ptoo.components.KButton newGame_Sources_kBttnBack;
    private com.k33ptoo.components.KButton newGame_Sources_kBttnNext;
    private javax.swing.JLayeredPane newGame_jLyrdPn;
    private com.k33ptoo.components.KGradientPanel newGame_kGrdntPnlCategories;
    private com.k33ptoo.components.KGradientPanel newGame_kGrdntPnlGameName;
    private com.k33ptoo.components.KGradientPanel newGame_kGrdntPnlSources;
    private javax.swing.JLabel settings_JLblLogo;
    private javax.swing.JLabel settings_jLblClearGames;
    private javax.swing.JLabel settings_jLblClearQuestion;
    private javax.swing.JLabel settings_jLblImportQuizzes;
    private javax.swing.JLabel settings_jLblImportQuizzesFromNapiKviz;
    private com.k33ptoo.components.KButton settings_kBttnBack;
    private com.k33ptoo.components.KButton settings_kBttnClearGames;
    private com.k33ptoo.components.KButton settings_kBttnClearQuestion;
    private com.k33ptoo.components.KButton settings_kBttnImportQuizzes;
    private com.k33ptoo.components.KButton settings_kBttnImportQuizzesFromNapiKviz;
    private com.k33ptoo.components.KGradientPanel settings_kGrdntPnl;
    // End of variables declaration//GEN-END:variables
}
