/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Data.DrinQuizContext;
import static Helpers.GameHandler.gameHandlerInstance;
import Helpers.ViewHelper;
import static Helpers.ViewHelper.infoBox;
import Models.Question;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Jani
 */
public class JFramePlayer extends javax.swing.JFrame {

    int frameHeight, frameWidth;
    
    /**
     * Creates new form JFramePlayer
     */
    public JFramePlayer() {
        initComponents();
        showOnScreen(0, this);

        endGame_kGrdntPnl.setVisible(false);
        game_kGrdntPnl.setVisible(false);
        scores_kGrdntPnl.setVisible(false);

        newPlayer_kGrdntPnl.setLayout(null);
        endGame_kGrdntPnl.setLayout(null);
        game_kGrdntPnl.setLayout(null);
        scores_kGrdntPnl.setLayout(null);

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();

        setPreferredSize(dimension);

        pack();

        frameWidth = dimension.width;
        frameHeight = dimension.height;

        changeLocation(newPlayer_jTxtFldPlayerName, 0, 0);
        changeLocation(newPlayer_kBttnStart, 0, 80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLyrdPn = new javax.swing.JLayeredPane();
        newPlayer_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        newPlayer_jTxtFldPlayerName = new javax.swing.JTextField();
        newPlayer_kBttnStart = new com.k33ptoo.components.KButton();
        game_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        endGame_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();
        scores_kGrdntPnl = new com.k33ptoo.components.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        newPlayer_jTxtFldPlayerName.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newPlayer_jTxtFldPlayerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newPlayer_jTxtFldPlayerName.setText("Írd be a neved!");
        newPlayer_jTxtFldPlayerName.setPreferredSize(new java.awt.Dimension(300, 50));
        newPlayer_jTxtFldPlayerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPlayer_jTxtFldPlayerNameMouseClicked(evt);
            }
        });

        newPlayer_kBttnStart.setBorder(null);
        newPlayer_kBttnStart.setText("Játék indítása");
        newPlayer_kBttnStart.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        newPlayer_kBttnStart.setkBorderRadius(50);
        newPlayer_kBttnStart.setPreferredSize(new java.awt.Dimension(200, 50));
        newPlayer_kBttnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPlayer_kBttnStartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout newPlayer_kGrdntPnlLayout = new javax.swing.GroupLayout(newPlayer_kGrdntPnl);
        newPlayer_kGrdntPnl.setLayout(newPlayer_kGrdntPnlLayout);
        newPlayer_kGrdntPnlLayout.setHorizontalGroup(
            newPlayer_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                .addGroup(newPlayer_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(newPlayer_jTxtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(newPlayer_kBttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(511, Short.MAX_VALUE))
        );
        newPlayer_kGrdntPnlLayout.setVerticalGroup(
            newPlayer_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPlayer_kGrdntPnlLayout.createSequentialGroup()
                .addContainerGap(529, Short.MAX_VALUE)
                .addComponent(newPlayer_jTxtFldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(newPlayer_kBttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout game_kGrdntPnlLayout = new javax.swing.GroupLayout(game_kGrdntPnl);
        game_kGrdntPnl.setLayout(game_kGrdntPnlLayout);
        game_kGrdntPnlLayout.setHorizontalGroup(
            game_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        game_kGrdntPnlLayout.setVerticalGroup(
            game_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout endGame_kGrdntPnlLayout = new javax.swing.GroupLayout(endGame_kGrdntPnl);
        endGame_kGrdntPnl.setLayout(endGame_kGrdntPnlLayout);
        endGame_kGrdntPnlLayout.setHorizontalGroup(
            endGame_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        endGame_kGrdntPnlLayout.setVerticalGroup(
            endGame_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout scores_kGrdntPnlLayout = new javax.swing.GroupLayout(scores_kGrdntPnl);
        scores_kGrdntPnl.setLayout(scores_kGrdntPnlLayout);
        scores_kGrdntPnlLayout.setHorizontalGroup(
            scores_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        scores_kGrdntPnlLayout.setVerticalGroup(
            scores_kGrdntPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLyrdPn.setLayer(newPlayer_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(game_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(endGame_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLyrdPn.setLayer(scores_kGrdntPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLyrdPnLayout = new javax.swing.GroupLayout(jLyrdPn);
        jLyrdPn.setLayout(jLyrdPnLayout);
        jLyrdPnLayout.setHorizontalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newPlayer_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(game_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(endGame_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scores_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLyrdPnLayout.setVerticalGroup(
            jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newPlayer_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(game_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(endGame_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLyrdPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scores_kGrdntPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLyrdPn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLyrdPn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPlayer_jTxtFldPlayerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPlayer_jTxtFldPlayerNameMouseClicked
        // TODO add your handling code here:
        if (newPlayer_jTxtFldPlayerName.getText().equals("Írd be a neved!")) {
            newPlayer_jTxtFldPlayerName.setText("");
        }
    }//GEN-LAST:event_newPlayer_jTxtFldPlayerNameMouseClicked

    private void newPlayer_kBttnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPlayer_kBttnStartMouseClicked
        // TODO add your handling code here:
        String playerName =newPlayer_jTxtFldPlayerName.getText();
        if(playerName.equals("") ||  playerName.equals("Írd be a neved!")){
            infoBox("Nem adtál meg nevet!");
            return;
        }
        
        gameHandlerInstance.createPlayer(playerName);
        newPlayer_kGrdntPnl.setVisible(false);
        game_kGrdntPnl.setVisible(true);
        
        
        ///Teszt a teljes új kérdés generálására, lekérdezésére, és megválaszolására
//        try {
//            gameHandlerInstance.getNewQuestion();
//        } catch (Exception ex) {
//            Logger.getLogger(JFramePlayer.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        Question q = gameHandlerInstance.getQuestion();
//        System.out.println("ID:        | " + q.getID());
//            System.out.println("Question:  | " + q.getQuestion());
//            System.out.println("Answers:   | " + q.getAnswers());
//            System.out.println("RAnswerID: | " + q.getRightAnswerID());
//            System.out.println("Category:  | " + q.getCategory());
//            System.out.println("Source:    | " + q.getSource());
//            System.out.println("\n");
//        gameHandlerInstance.answerQuestion(new String[]{"1","2","3"});
    }//GEN-LAST:event_newPlayer_kBttnStartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePlayer().setVisible(true);
            }
        });
    }

    ///SAJÁT ELJÁRÁSOK
    void changeLocation(Component comp, int width, int height) {
        comp.setLocation(frameWidth / 2 - comp.getWidth() / 2 + width,
                 frameHeight / 2 - comp.getHeight() / 2 + height);
    }
    
    ///SAJÁT ELJÁRÁSOK VÉGE
    
    public static void showOnScreen(int screen, JFrame frame) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gd = ge.getScreenDevices();

        if (screen > -1 && screen < gd.length) {
            //gd[screen].setFullScreenWindow(frame);
            frame.setLocation(gd[screen].getDefaultConfiguration().getBounds().x, frame.getY());
        } else if (gd.length > 0) {
            //gd[0].setFullScreenWindow(frame);
            frame.setLocation(gd[0].getDefaultConfiguration().getBounds().x, frame.getY());
        } else {
            throw new RuntimeException("No screen found!");

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel endGame_kGrdntPnl;
    private com.k33ptoo.components.KGradientPanel game_kGrdntPnl;
    private javax.swing.JLayeredPane jLyrdPn;
    private javax.swing.JTextField newPlayer_jTxtFldPlayerName;
    private com.k33ptoo.components.KButton newPlayer_kBttnStart;
    private com.k33ptoo.components.KGradientPanel newPlayer_kGrdntPnl;
    private com.k33ptoo.components.KGradientPanel scores_kGrdntPnl;
    // End of variables declaration//GEN-END:variables
}
