/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.HostJPanels;

import java.awt.Frame;
import javax.swing.WindowConstants;

/**
 *
 * @author Jani
 */
public class JPanelMainMenu extends javax.swing.JPanel {

    /**
     * Creates new form mainMenu
     */
    public JPanelMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameButton = new com.k33ptoo.components.KButton();
        loadButton = new com.k33ptoo.components.KButton();
        settingsButton = new com.k33ptoo.components.KButton();
        exitButton = new com.k33ptoo.components.KButton();

        gameButton.setBorder(null);
        gameButton.setText("New Game");
        gameButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        gameButton.setkBorderRadius(50);
        gameButton.setPreferredSize(new java.awt.Dimension(200, 50));
        gameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonMouseClicked(evt);
            }
        });

        loadButton.setBorder(null);
        loadButton.setText("Load Game");
        loadButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        loadButton.setkBorderRadius(50);
        loadButton.setPreferredSize(new java.awt.Dimension(200, 50));

        settingsButton.setBorder(null);
        settingsButton.setText("Settings");
        settingsButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        settingsButton.setkBorderRadius(50);
        settingsButton.setPreferredSize(new java.awt.Dimension(200, 50));

        exitButton.setBorder(null);
        exitButton.setText("Exit");
        exitButton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        exitButton.setkBorderRadius(50);
        exitButton.setPreferredSize(new java.awt.Dimension(200, 50));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void gameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_gameButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton exitButton;
    public com.k33ptoo.components.KButton gameButton;
    private com.k33ptoo.components.KButton loadButton;
    private com.k33ptoo.components.KButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
