/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;

import java.awt.Component;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jani
 */
public class HostJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HostJFrame
     */
    public HostJFrame() {
        this.logo = new ImageIcon("/resources/images/icon.png");
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane = new javax.swing.JLayeredPane();
        mainPanel = new com.k33ptoo.components.KGradientPanel();
        gameButton = new com.k33ptoo.components.KButton();
        settingsButton = new com.k33ptoo.components.KButton();
        exitButton = new com.k33ptoo.components.KButton();
        loadButton = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(logo.getImage());

        mainPanel.setAlignmentX(Component.CENTER_ALIGNMENT);
        mainPanel.setAlignmentY(Component.CENTER_ALIGNMENT);
        mainPanel.setkEndColor(new java.awt.Color(201, 0, 53));
        mainPanel.setkStartColor(new java.awt.Color(91, 22, 71));

        gameButton.setText("New Game");
        gameButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        gameButton.setAlignmentY(Component.CENTER_ALIGNMENT);
        gameButton.setBorderPainted(false);
        gameButton.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        gameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameButton.setkBorderRadius(50);
        gameButton.setkEndColor(new java.awt.Color(69, 30, 62));
        gameButton.setkHoverEndColor(new java.awt.Color(23, 7, 43));
        gameButton.setkHoverStartColor(new java.awt.Color(140, 21, 233));
        gameButton.setkStartColor(new java.awt.Color(6, 30, 63));
        gameButton.setMargin(new java.awt.Insets(8, 16, 8, 16));
        gameButton.setMaximumSize(new java.awt.Dimension(175, 50));
        gameButton.setMinimumSize(new java.awt.Dimension(175, 50));
        gameButton.setPreferredSize(new java.awt.Dimension(175, 50));
        gameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonMouseClicked(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        settingsButton.setAlignmentY(Component.CENTER_ALIGNMENT);
        settingsButton.setBorderPainted(false);
        settingsButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        settingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        settingsButton.setkBorderRadius(50);
        settingsButton.setkEndColor(new java.awt.Color(60, 30, 62));
        settingsButton.setkHoverEndColor(new java.awt.Color(23, 7, 43));
        settingsButton.setkHoverStartColor(new java.awt.Color(140, 21, 233));
        settingsButton.setkStartColor(new java.awt.Color(6, 30, 63));
        settingsButton.setMargin(new java.awt.Insets(8, 16, 8, 16));
        settingsButton.setMaximumSize(new java.awt.Dimension(175, 50));
        settingsButton.setMinimumSize(new java.awt.Dimension(175, 50));
        settingsButton.setPreferredSize(new java.awt.Dimension(175, 50));

        exitButton.setText("Exit");
        exitButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        exitButton.setAlignmentY(Component.CENTER_ALIGNMENT);
        exitButton.setBorderPainted(false);
        exitButton.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setkBorderRadius(50);
        exitButton.setkEndColor(new java.awt.Color(60, 30, 62));
        exitButton.setkHoverEndColor(new java.awt.Color(23, 7, 43));
        exitButton.setkHoverStartColor(new java.awt.Color(140, 21, 233));
        exitButton.setkStartColor(new java.awt.Color(6, 30, 63));
        exitButton.setMargin(new java.awt.Insets(8, 16, 8, 16));
        exitButton.setMaximumSize(new java.awt.Dimension(175, 50));
        exitButton.setMinimumSize(new java.awt.Dimension(175, 50));
        exitButton.setPreferredSize(new java.awt.Dimension(175, 50));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        loadButton.setText("Load Game");
        loadButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        loadButton.setAlignmentY(Component.CENTER_ALIGNMENT);
        loadButton.setBorderPainted(false);
        loadButton.setContentAreaFilled(false);
        loadButton.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        loadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadButton.setkBorderRadius(50);
        loadButton.setkEndColor(new java.awt.Color(69, 30, 62));
        loadButton.setkHoverEndColor(new java.awt.Color(23, 7, 43));
        loadButton.setkHoverStartColor(new java.awt.Color(140, 21, 233));
        loadButton.setkStartColor(new java.awt.Color(6, 30, 63));
        loadButton.setMargin(new java.awt.Insets(8, 16, 8, 16));
        loadButton.setMaximumSize(new java.awt.Dimension(175, 50));
        loadButton.setMinimumSize(new java.awt.Dimension(175, 50));
        loadButton.setPreferredSize(new java.awt.Dimension(175, 50));
        loadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        gameButton.getAccessibleContext().setAccessibleName("gameButton");
        settingsButton.getAccessibleContext().setAccessibleName("settingsButton");
        exitButton.getAccessibleContext().setAccessibleName("exitButton");
        loadButton.getAccessibleContext().setAccessibleName("loadButton");

        jLayeredPane.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneLayout = new javax.swing.GroupLayout(jLayeredPane);
        jLayeredPane.setLayout(jLayeredPaneLayout);
        jLayeredPaneLayout.setHorizontalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneLayout.setVerticalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneLayout.createSequentialGroup()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void gameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                PlayerJFrame playerJFrame = new PlayerJFrame();
                playerJFrame.setVisible(true);
            }
        });
    }//GEN-LAST:event_gameButtonMouseClicked

    private void loadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loadButtonMouseClicked

    ImageIcon logo = new ImageIcon(".//resources/images/icon.png");

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton exitButton;
    private com.k33ptoo.components.KButton gameButton;
    private javax.swing.JLayeredPane jLayeredPane;
    private com.k33ptoo.components.KButton loadButton;
    private com.k33ptoo.components.KGradientPanel mainPanel;
    private com.k33ptoo.components.KButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
